### ISSUE TITLE
Function pointers are not generated correctly

### ISSUE THREAD

**Issue by christophschlosser** [christophschlosser/doxdocgen#18]
Example:
```C
int (*idputs(int (*puts)(const char *)))(const char *);
```

**Comment by rowanG077** [comment]
You are right that maybe we can just say not to support output of function pointers. I have tried to implement it for a couple of hours now but can't seem to find a good way. 

I have made an issue on the C/C++ language support git from MS. Maybe we can leverage their API to parse functions for us. https://github.com/Microsoft/vscode-cpptools/issues/1136

**Comment by rowanG077** [comment]
I have also looked at this: https://shaharmike.com/cpp/libclang/

I havent' used it yet but will do some experiments tommorow. Might solve all our problems.

**Comment by rizickus** [comment]
Any result using libclang or plans for integration into plugin?
Parsing C++ is a tricky job and using only regex will not cover most of the cases.

**Comment by rowanG077** [comment]
@rizickus 

It won't work since libclang requires the entire source tree to be parsed. Doing that would require reparsing the tree each time a comment wants to be generated. We could do it by implementing another language server just for this but that seems overkill.

I am currently busy rewriting the parser using a small lexer and some heuristics. It should be done today or tommorow. This will include template parsing. correct function pointer parsing.

**Comment by rowanG077** [comment]
@rizickus Sorry it took longer to implement. Had to try 3 different solutions to finally be able to support all to me known scenarios.

Fixed in pull request: https://github.com/christophschlosser/doxdocgen/pull/23
