### ISSUE TITLE
Ability to update the version number without editing it yourself

### ISSUE THREAD

**Issue by muisje** [christophschlosser/doxdocgen#95]
# Description

Ability to update the version number without editing it yourself.

When i was configuring doxdoc in vscode i saw that version number was 'hard coded' and didn't see a way to make it variable. 

Options:

I would like to see:
- On save
- On command
- On Keyboard shortcut

These things could be nice to have: (but can be achievable e.g. git hooks)
- On git Commit
- On git Push

## Code example

```Cpp
/**
 * @version 0.1
 */
```

### Expected result

```Cpp
/**
 * @version 0.2
 */
```

### Actual result

```Cpp
/**
 * @version 0.1
 */
```

**Comment by christophschlosser** [comment]
What would you like to see on these options?
How should the addon know what to increment?

I'm gonna be honest but this seems like a feature that is hard to do right for everybody because of different versioning schemes and so on. Having the number/string as a setting is already pretty flexible.

Probably the easiest way for you is to have a git hook run a search and replace.
